### ISSUE TITLE
Unclear where to add datasource for bots created in UI

### ISSUE THREAD

**Issue by steviedrew67** [run-llama/chat-llamaindex#22]
First of all, thanks for the great solution.

Everything is running fine locally but I'm not clear where to edit the bots created from the UI. When I go to the apps/bots/bot.data.ts i do not see the bot I created and when I edit one of the demo bots in that file I don't see the changes in the UI.

**Comment by SamirTafesh** [comment]
Same issue, i am facing, not able to remove or update the DEMO Bots

**Comment by marcusschiesser** [comment]
Thanks for your help here @SamirTafesh. The two of you didn't see the updates of the `bot.data.ts` file because the bots are stored in local storage. Local storage needs to be cleared to see any changes. 

I updated the readme:

https://github.com/run-llama/chat-llamaindex/blob/bcea837b17ec9f1d0a58c71cd3a78e9e7cc75147/README.md?plain=1#L81
